import './globals.scss'
import type { Metadata } from 'next'
import { Providers } from './Provider'

export const metadata: Metadata = {
  title: 'Data table',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='container'>
          <Providers>
            {children}
          </Providers>
        </div>
      </body>
    </html>
  )
}
